# Generated by Django 4.0.7 on 2022-09-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='user',
            new_name='user_id',
        ),
    ]
