# Generated by Django 4.0.7 on 2022-09-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField()),
                ('energy_consumption', models.FloatField()),
            ],
        ),
    ]
