# Generated by Django 4.0.7 on 2022-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='request_url',
            field=models.CharField(max_length=255),
        ),
    ]
